Add go.mod
Makes it possible to compile and work on it outside GOPATH. Also records
versions of dependencies.

Fixed two errors reported by "go vet" (which is run on "go test" since
Go 1.11):

	$ go test
	# github.com/mytchel/pass
	./commands.go:141:21: Errorf call has arguments but no formatting directives
	./commands.go:215:2: Println arg list ends with redundant newline